# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backup and Merge

on:
  push:
    branches: [ main ]

jobs:
  backup-and-merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.16.0]
        # suitecloud-cli requires 14.16.0
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update Ubuntu packages
      run: sudo apt update -y
    - name: Set time zone
      run: sudo timedatectl set-timezone America/New_York
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet zip gzip tar
    - name: Install suitecloud-cli
      run: npm install -g @oracle/suitecloud-cli --unsafe --acceptsuitecloudsdklicense --supressSuiteCloudSDKLicensePrompt
    - name: Install suitecloud-unit-testing
      run: npm install -g @oracle/suitecloud-unit-testing
    - name: NPM install
      run: npm install
    - name: Run code tests
      run: npm run test
    - name: Backup NetSuite scripts and records to be deployed
      run: |
        sudo chmod 755 .github/scripts/sdf-backup.sh
        .github/scripts/sdf-backup.sh ${{ secrets.SDF_USER_PROD_KEY }} ${{ secrets.SDF_USER_PROD_SECRET }} ${{ secrets.SDF_ACCOUNT_NUMBER }}
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "/home/runner/work/woodland-sdf-github-actions-demo/woodland-sdf-github-actions-demo/backup/"
        DEST_DIR: "netsuite/backup"
    - name: Deploy NetSuite scripts
      run: |
        sudo chmod 755 .github/scripts/sdf-deploy.sh
        .github/scripts/sdf-deploy.sh ${{ secrets.SDF_USER_PROD_KEY }} ${{ secrets.SDF_USER_PROD_SECRET }} ${{ secrets.SDF_ACCOUNT_NUMBER }}